AllCops:
  Exclude:
    - 'tryout/**/*'
    - "vendor/**/.*"
    - "vendor/**/*"
  NewCops: enable

inherit_from: .rubocop_todo.yml

Style/DoubleNegation:
  Exclude:
    - 'lib/net/ssh/key_factory.rb'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
    - 'net-ssh.gemspec'
