VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
    ansible.sudo = true
    ansible.verbose ='vvvv'
  end

  config.vm.synced_folder "../..", "/net-ssh"
end